version: 2
multi-ecosystem-groups:
  ruff:
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      actions:
        update-types:
          - minor
          - patch
        patterns:
          - "actions/*"
          - "release-drafter/*"
          - "peter-evans/*"
          - "syphar/*"
          - "dorny/*"
          - "orgoro/*"
          - "astral-sh/*"
    cooldown:
      default-days: 7

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      python-dependencies:
        update-types:
          - minor
          - patch
    cooldown:
      default-days: 7

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
    
  - package-ecosystem: "uv"
    directory: "/"
    patterns: ["ruff"]
    multi-ecosystem-group: "ruff"
    cooldown:
      default-days: 7
  
  - package-ecosystem: "pre-commit"
    directory: "/"
    patterns: ["*/astral-sh/ruff-pre-commit"]
    multi-ecosystem-group: "ruff"
    cooldown:
      default-days: 7
