version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      actions:
        patterns:
          - "actions/*"
          - "release-drafter/*"
          - "peter-evans/*"
          - "syphar/*"
          - "dorny/*"
          - "orgoro/*"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
