---
repos:
  - hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
        files: ^((pygleif|tests|examples)/.+)?[^/]+\.(py|pyi)$
    repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.15.22
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: requirements-txt-fixer
      - id: check-ast
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
        exclude: (.vscode|.devcontainer)
      - id: no-commit-to-branch
        args:
          - --branch=main
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.27.0
    hooks:
    - id: zizmor
  - repo: local
    hooks:
      - id: ty
        name: ty
        entry: >
          ./.devcontainer/run-in-env.sh ty check
        language: script
        types: [python]
        require_serial: true
        files: ^pygleif/.+\.py$
