FROM mcr.microsoft.com/vscode/devcontainers/python:3.11-bullseye
LABEL author="NCR"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN pip install pip setuptools wheel cython

ENV FILE_LOCATION "/usr/src/app"

# Disable host checking
RUN mkdir -p /root/.ssh && \
    echo "Host *" >> /root/.ssh/config && \
    echo "StrictHostKeyChecking no" >> /root/.ssh/config

COPY . $FILE_LOCATION

WORKDIR $FILE_LOCATION/

# Set the default shell to bash instead of sh
ENV SHELL /bin/bash
