FROM mcr.microsoft.com/vscode/devcontainers/python:3.13-bullseye
LABEL author="PL"

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/

ENV FILE_LOCATION "/usr/src/app"

COPY . $FILE_LOCATION

WORKDIR $FILE_LOCATION/
