name: Code quality tests

env:
  ALL_PYTHON_VERSIONS: "['3.11', '3.12']"
  CACHE_VERSION: 1

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  info:
    runs-on: ubuntu-latest
    name: Collect information & changes data
    outputs:
      run_pipeline: ${{ steps.changes.outputs.core }}
      python_versions: ${{ steps.info.outputs.python_versions }}
      python_cache_key: ${{ steps.generate_python_cache_key.outputs.key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Filter for core changes
        uses: dorny/paths-filter@v3.0.2
        id: changes
        with:
          filters: |
            core:
              - ./**/*.py
              - .github/**/*.yml
              - pyproject.toml

      - name: Generate partial Python venv restore key
        id: generate_python_cache_key
        run: >-
          echo "key=venv-${{ env.CACHE_VERSION }}-${{
            hashFiles('pyproject.toml') }}" >> $GITHUB_OUTPUT

      - name: Collect additional information
        id: info
        run: |
          echo "python_versions: ${ALL_PYTHON_VERSIONS}"
          echo "python_versions=${ALL_PYTHON_VERSIONS}" >> $GITHUB_OUTPUT

  create-virtualenv:
    name: Setup environment
    runs-on: ubuntu-latest
    needs: info
    timeout-minutes: 10
    if: needs.info.outputs.run_pipeline == 'true'
    strategy:
      matrix:
        python-version: ${{ fromJSON(needs.info.outputs.python_versions) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Python ${{ matrix.python-version }}
        id: python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Restore base Python virtual environment
        id: cache-venv
        uses: actions/cache@v4.0.2
        with:
          path: .venv
          lookup-only: true
          key: >-
            ${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{
            needs.info.outputs.python_cache_key }}

      - name: Install requirements
        run: |
          python -m pip install uv

          uv venv  # Create a virtual environment at .venv.

          source .venv/bin/activate

          uv pip install -e .'[test]'
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

  linter:
    name: Run code linters
    needs:
      - create-virtualenv
      - info
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ${{ fromJSON(needs.info.outputs.python_versions) }}
    if: needs.info.outputs.run_pipeline == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: "2"
      - name: Set up Python ${{ matrix.python-version }}
        id: python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Restore full Python ${{ steps.python.outputs.python-version }} virtual environment
        id: cache-venv
        uses: actions/cache/restore@v4.0.2
        with:
          path: .venv
          fail-on-cache-miss: true
          key: >-
            ${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{
            needs.info.outputs.python_cache_key }}
      - name: Run ruff
        run: |
          source .venv/bin/activate
          pre-commit run --hook-stage manual ruff --all-files --show-diff-on-failure
        env:
          RUFF_OUTPUT_FORMAT: github
      - name: Run ruff-format
        run: |
          source .venv/bin/activate
          pre-commit run --hook-stage manual ruff-format --all-files --show-diff-on-failure
        env:
          RUFF_OUTPUT_FORMAT: github
      - name: Run mypy
        run: |
          source .venv/bin/activate
          pre-commit run --hook-stage manual mypy --all-files --show-diff-on-failure

  pytest:
    name: Run test suite
    continue-on-error: true
    needs:
      - info
      - create-virtualenv
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ${{ fromJSON(needs.info.outputs.python_versions) }}
    if: needs.info.outputs.run_pipeline == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Python ${{ matrix.python-version }}
        id: python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Restore full Python ${{ steps.python.outputs.python-version }} virtual environment
        id: cache-venv
        uses: actions/cache/restore@v4.0.2
        with:
          path: .venv
          fail-on-cache-miss: true
          key: >-
            ${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{
            needs.info.outputs.python_cache_key }}

      - name: Run tests
        run: |
          source .venv/bin/activate

          pytest tests/ --cov pygleif --cov-report xml:coverage.xml

      - name: Post coverage
        uses: orgoro/coverage@v3
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
